version: "3.9"

services:
  identity_db:
    container_name: identity_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./Data/Identity:/var/opt/mssql/data
    ports:
      - 8000:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"

  entry_db:
    container_name: entry_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./Data/Entry:/var/opt/mssql/data
    ports:
      - 8001:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"

  category_db:
    container_name: category_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./Data/Category:/var/opt/mssql/data
    ports:
      - 8002:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"
  
  rabbitmq_broker:
    container_name: rabbitmq_broker
    image: rabbitmq:4-management
    hostname: rabbitmq
    restart: always
    volumes:
      - ./Data/RabbitMQ:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=HHHHhhhh1111